<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="9.8830" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2022-07-05T05:30:19" tests="0" file="cypress\e2e\secondTest.cy.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2022-07-05T05:30:19" tests="1" time="9.8370" failures="1">
    <testcase name="Test log out Verify user can logout sucessfully" time="0.0000" classname="Verify user can logout sucessfully">
      <failure message="Timed out retrying after 4000ms: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos; Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain ' Sign up1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress\e2e\secondTest.cy.js:106:27)]]></failure>
    </testcase>
  </testsuite>
</testsuites>